# production: &production
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: datcord_production
#
# development: &development
#   adapter: redis
#   url: redis://localhost:6397
#
# test: *development
